### PR TITLE
Fixed rendering of directory indices.

### LINKED ISSUE #3: Broken directory index with latest release
Hi,

when I am trying to open a bucket that has no index.html I currently get {"level":"error","msg":"Serve[/iso] [500]: http: wrote more than the declared Content-Length"} -- I think somehow the default headers that are set don't consider the possibility that minio-web writes something else… I tried to get the project to compile locally but I am ending up in a go depedency hell and I am not sure how to proceed :) I'd happily supply a fix for the issue itself if it were possible that you can fix up go.mod so I can compile master.

Thank you for this project.

### PR DESCRIPTION
**Pull request by apollo13**
Fixes #3

### CODE REVIEW

**Comment by apollo13** [comment]
Hi @eterna2, I think I have pushed through all the issue and it now works as expected. Could you take a look? :)

**Comment by apollo13** [comment]
While it seems to work I am getting 
app_1  | {"level":"error","msg":"Serve[/iso/stable/] [500]: http: wrote more than the declared Content-Length"}

in the log (even though it serves fine) and I am not yet sure where it comes from.

**Comment by apollo13** [comment]
Fixed the logging issue with the last commit.

**Review by eterna2 — APPROVED** [review]
LGTM.

Thanks for the fix! 

Yeah it was a pain cuz micro redesigned their project structure.

**Pull request merged**
